### ISSUE TITLE
"An unexpected error happened" while saving a new dashboard

### ISSUE THREAD

**Issue by fridgepoet** [grafana/iot-sitewise-datasource#242]
**What happened**:
While following "build a new dashboard" from the config page, when saving the dashboard, a *second* save window appears and following that will lead to "An unexpected error happened, DetailsTypeError: Cannot add property isHandled, object is not extensible"

**What you expected to happen**:
The first dashboard save is successful.

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to config page
2. Click Save and test
3. Click Build a Dashboard
4. Add a SiteWise visualization
5. Click Save and enter a title and Save.
6. At this point, you should see another Save pop-up and clicking Save dashboard there will lead to the error.

Here's a recording:

https://github.com/grafana/iot-sitewise-datasource/assets/4163034/c41ef321-5310-47a1-8bc2-8436a7a468cb

**Anything else we need to know?**:
```
An unexpected error happened
DetailsTypeError: Cannot add property isHandled, object is not extensible

    at SaveDashboardErrorProxy (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:135433:3)
    at SaveDashboardDrawer (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:135310:32)
    at ModalRoot
    at ModalsProvider (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:72141:5)
    at KBarProvider (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:234767:48)
    at SkeletonTheme (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:603656:26)
    at ThemeProvider (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:113719:26)
    at ErrorBoundary (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:64658:5)
    at ErrorBoundaryAlert (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:64696:1)
    at Provider (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:322270:3)
    at AppWrapper (http://localhost:3000/public/build/app.b73eec78fb7eb530db6d.js:94262:5)

```

**Environment**:
- Grafana version: v10.3.0-pre
- Plugin version: latest at commit https://github.com/grafana/iot-sitewise-datasource/tree/cdd0c6ddf29e9d9da3db05a010aedc36f4269116
- OS Grafana is installed on: MacOS, local build
- User OS & Browser: MacOS and Chrome

**Comment by fridgepoet** [comment]
This seems to be an issue in main Grafana which has already been resolved https://github.com/grafana/grafana/pull/77620
